name: htocsp
channels:
  - conda-forge
dependencies:
  - python>=3.11.0
  - parmed=4.3.0
  - openmm=8.0.0
  - openbabel=3.1.1
  - openff-forcefields=2023.04.1
  - openff-toolkit=0.17.0
  - openff-models=0.1.0 
  - openff-units=0.2.0
  - openff-utilities=0.1.8
  - openff-interchange=0.4.8
  - toml=0.10.2
  - xmltodict=0.13.0
  #Dev tools at github commit
  - pip:
    - numpy==2.2.5
    - scipy==1.16.3
    - pyxtal==1.1.2
    - pyocse==0.1.3
    - git+https://github.com/ACEsuit/mace@main
    - e3nn==0.4.4
    - torch-dftd==0.4.0
    - pint==0.25.2
    - torchani
    - seaborn
  - black
  - flake8
  - isort
  - pre-commit
  - pytest
  - pytest-cov
  - pdoc3
